//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sad.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class hvoysvet
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> tipprod { get; set; }
        public string tipproduname { get; set; }
        public string poliv { get; set; }
        public string cena { get; set; }
        public string vozrast { get; set; }
        public string image { get; set; }
    }
}
