//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sad.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sadEntities : DbContext
    {
        public sadEntities()
            : base("name=sadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<progekt> progekt { get; set; }
        public virtual DbSet<productnotrost> productnotrost { get; set; }
        public virtual DbSet<hvoysvet> hvoysvet { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
