//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sad.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class productnotrost
    {
        public int Id { get; set; }
        public Nullable<int> tipProduct { get; set; }
        public string tipProductname { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string images { get; set; }
    }
}
