//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sad.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class progekt
    {
        public int Id { get; set; }
        public string image { get; set; }
        public string op { get; set; }
        public string gorod { get; set; }
        public string god { get; set; }
        public string tipproe { get; set; }
        public string tipprodukct { get; set; }
        public Nullable<int> tip { get; set; }
    }
}
